services:
  - type: web
    name: edustreamix-web
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://admin:parimala%40888@project1.ixuccs7.mongodb.net/edustreamix?retryWrites=true&w=majority&appName=Project1
      - key: GEMINI_API_KEY
        value: AIzaSyDoj644WpfTgz224pTMXwcsks8sEhWU28k
